language: php

php:
  - '7.1'
  - '7.2'

install:
  - composer install

script: 
  - mkdir -p build/logs
  - vendor/bin/phpunit tests/ArrayTest.php
  - vendor/bin/phpunit tests/MatrixTest.php

after_success:
  - travis_retry php vendor/bin/coveralls